-- MySQL Script generated by MySQL Workbench
-- Mon Mar 30 10:08:04 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema timetracking
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema timetracking
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `timetracking` DEFAULT CHARACTER SET utf8 ;
USE `timetracking` ;

-- -----------------------------------------------------
-- Table `timetracking`.`proiecte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `timetracking`.`proiecte` (
  `cod_proiect` VARCHAR(16) NOT NULL UNIQUE,
  `nume` VARCHAR(45) NULL,
  `data_creare` DATETIME NULL,
  `urmatorul_milestone` DATETIME NULL,
  PRIMARY KEY (`cod_proiect`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `timetracking`.`Companii`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `timetracking`.`Companii` (
  `id_companie` INT NOT NULL AUTO_INCREMENT,
  `user` VARCHAR(45) NOT NULL UNIQUE,
  `parola` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_companie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `timetracking`.`Invitatii`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `timetracking`.`Invitatii` (
  `id_invitatie` VARCHAR(64) NOT NULL UNIQUE,
  `invitatie_folosita` TINYINT(1) NOT NULL DEFAULT 0,
  `id_companie` INT NULL,
  PRIMARY KEY (`id_invitatie`),


  CONSTRAINT `fk_comp`
    FOREIGN KEY (`id_companie`)
    REFERENCES `timetracking`.`Companii` (`id_companie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `timetracking`.`Angajati`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `timetracking`.`Angajati` (
  `id_angajat` INT NOT NULL AUTO_INCREMENT,
  `id_invitatie` VARCHAR(64) NULL,
  `nickname` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `parola` VARCHAR(45) NULL,

  PRIMARY KEY (`id_angajat`),
 
  CONSTRAINT `fk_invitatii`
    FOREIGN KEY (`id_invitatie`)
    REFERENCES `timetracking`.`Invitatii` (`id_invitatie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
 
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `timetracking`.`angajat_proiect`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `timetracking`.`angajat_proiect` (
  `id_ap` INT NOT NULL AUTO_INCREMENT,
  `id_angajat` INT NOT NULL,
  `cod_proiect` VARCHAR(16) NOT NULL,
  `data_inrolarii` DATETIME NOT NULL,
  `data_parasire` DATETIME NULL,
  PRIMARY KEY (`id_ap`),

  CONSTRAINT `fk_angajat`
    FOREIGN KEY (`id_angajat`)
    REFERENCES `timetracking`.`Angajati` (`id_angajat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proiect`
    FOREIGN KEY (`cod_proiect`)
    REFERENCES `timetracking`.`proiecte` (`cod_proiect`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `timetracking`.`sesiuni`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `timetracking`.`sesiuni` (
  `id_sesiune` INT NOT NULL AUTO_INCREMENT,
  `timestamp_inceput` DATETIME NOT NULL,
  `timestamp_final` DATETIME NULL,
  `id_ap` INT NOT NULL,
  PRIMARY KEY (`id_sesiune`),

  CONSTRAINT `fk_sesiuni_1`
    FOREIGN KEY (`id_ap`)
    REFERENCES `timetracking`.`angajat_proiect` (`id_ap`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
